# Generated by Django 3.2.4 on 2021-06-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_posts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post',
            new_name='body',
        ),
    ]
