# Generated by Django 3.2.4 on 2021-06-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_post_posts_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='categories',
        ),
        migrations.AddField(
            model_name='posts',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
            preserve_default=False,
        ),
    ]
